emweb/wt

cmake/WtFindMysql.txt
the lib path for mariadb was missing.
=> added mariadb to the lib path

src/Wt/Dbo/Query, src/Wt/Dbo/Query.C, src/Wt/Dbo/Query_impl.h
Allows Queries to have a 'having()' clause (similar to where() .. but for aggregate fields like 'count(x)' or 'sum(x)'.
=> Support for 'having' clause in queries

src/Wt/Dbo/backend/Sqlite3.C
When writing a specialization of ```sql_value_traits::bind``` where data is generated and stored in a local variable (i.e an encrypted field) I noticed that the persisted data in the db would often be corrupted.
In the sqlite backend implementation, ```SQLITE_STATIC``` was used as the storage specifier, which assumes that the bound data will remain allocated until the statement is finalized. However finalization occurs after the scope of the ```sql_value_traits::bind``` method.
I understand not wanting to create a temporary copy of blob data (which could be quite large) when binding, but this implicit requirement to handle allocation beyond the scope of ```sql_value_traits::bind``` is a nasty gotcha?
Thanks for taking a look!
=> WtDbo: Use SQLITE_TRANSIENT storage specifier for Sqlite blob binding

src/web/skeleton/Wt.js
I have not tested this under IE7, but this seems to be a typo.
=> Fix Typo for ieAlternative

src/Wt/WRasterImage-gm.C, src/fcgi/WServer.C
Fix a couple of typos in printed-out messages
=> Fix typo: unkown -> unknown

src/Wt/WSlider.C
this solves the sliderMoved() signal not working using a JSlot or a std::string js function with that signal ("JSignal: connect(JSlot): signal does not collect JavaScript from slots").
=> JSignal fix on WSlider

src/http/Configuration.C
Wt::WRun throws if unknown command line parameters are present. Since Wt::WRun() is mostly a helper function, silent-ignore behavior seems reasonable. According to http://www.boost.org/doc/libs/1_56_0/doc/html/program_options/howto.html#idp344642720 "To allow unregistered options on the command line, you need to use the basic_command_line_parser class for parsing (not parse_command_line) and call the allow_unregistered method of that class".
=> Wt::WRun throws on unknown command line parameters

src/Wt/Chart/WCartesian3DChart.C
"near" and "far" are defined in minwindef.h (mingw-w64):
#define far
#define near
Error message:
wt-3.3.4/src/Wt/Chart/WCartesian3DChart.C:330:16: error:
expected primary-expression before '(' token
WVector4 far(
^
=> WCartesian3DChart: rename variables near and far

src/Wt/Mail/Client
There are some missing closing brackets in Wt::Mail::Client Class Reference
=> fix-missing-brackets-client

src/Wt/Dbo/backend/MySQL.C
Changed storage_engine to default_storage_engine as first one
is [removed](http://mysqlserverteam.com/removal-and-deprecation-in-mysql-5-7/) in MySQL version 5.7.
Signed-off-by: Alexey Slaykovsky <alexey@slaykovsky.com>
=> MySQL DBO. Changed deprecated variable.

src/http/Configuration.C, src/http/Configuration.h, src/http/Server.C
I've added support for forward secrecy to wthttpd. An option to set server cipher order preference is added. In addition, SSL_CTX_set_ecdh_auto, if available, is set to 1. Web servers such as Apache and nginx also set this to 1 by default.
=> Add support for forward secrecy to wthttp

src/Wt/WGenericMatrix
Workaround issue when compiling with Boost 1.64. See here: http://redmine.webtoolkit.eu/boards/2/topics/13412
=> Workaround issue when compiling with Boost 1.64

src/Wt/Render/CssParser.C
One of my machines (2GB RAM, no swap) runs out of memory compiling CssParser.C. For Wt3 I could undefine CSS_PARSER in that file and compile a working library. For Wt4, I get a compile error (seems like someone forgot to upgrade this part of the code). Provided is a compile-fix.
=> Compile-fix for when CSS_PARSER is not defined

src/Wt/WTreeView.C
Pull Request fixing redmine issue #6261
https://redmine.webtoolkit.eu/issues/6261
`c0StyleRule_` got readded on every model change. 
In `~WCssRule` only the first occurence in `rules_` got erased.
In `~WApplication -> styleSheet_.clear(); -> ~WCssStyleSheet` -> crash because of deleting already deleted entry of rules_
There are severeal possibilities of fixing this, the one provided was the quickest for me.
Best regards,
Max
=> Fix issue #6261

src/Wt/WAbstractItemView.h
With Wt 4, ownership is made explicit, so no comment need be made
about how ownership works, or under what circumstances a model
will be deleted.
=> Corrected documentation about ownership transfer

src/http/Reply.C
A missing break was breaking the HTML reply by inserting two status lines instead of only one
=> Fix 500 status leading to invalid HTML reply [wt3]

src/http/Reply.C
A missing break was breaking the HTML reply by inserting two status lines instead of only one
=> Fix 500 status leading to invalid HTML reply [master]

src/Wt/Dbo/StringStream.h, src/Wt/WStringStream.C, src/Wt/WStringStream.h, src/web/EscapeOStream.C, src/web/EscapeOStream.h
Fix `WStringStream` to directly accept `const char *` strings.  
Remove overly greedy template overload `operator<<`.  
Remove string literal overload to reduce template bloat since there is now a `const char *` overload that can accept string literals.
=> Fix WStringStream to accept const char strings

src/Wt/WLocalDateTime.C, src/isapi/IsapiRequest.C, src/isapi/Server.C
follow-up on https://github.com/bincrafters/community/issues/353
main change is to use lower-case Windows headers names (e.g. Windows.h -> windows.h, ShlObj.h -> shlobj.h).
and few minor fixes - missing cstring include and implicit function pointer -> data pointer case.
to reproduce the following docker image may be used: https://hub.docker.com/r/bincrafters/docker-mingw-gcc7/
=> fixes for Linux MinGW (cross-compiling to Windows)

examples/te-benchmark/benchmark.cpp
I have noticed that you already have the same fix on the master branch, so that 4.x.x versions build fine on FreeBSD. But, 3.4.x version fails with this particular file.
=> fix freebsd build issue

wt-config.cmake.in
The expression
```
find_package(Boost QUIET COMPONENTS "@Boost_COMPONENTS@")
```
results in
```
find_package(Boost QUIET COMPONENTS "program_options;filesystem;thread")
```
according to the CMake documentation [1] and [2] is a list with one entry `"program_options;filesystem;thread"` and CMake is unable to find the component `"program_options;filesystem;thread"`
The correct form is
```
find_package(Boost QUIET COMPONENTS program_options;filesystem;thread)
```
Then CMake interprets `program_options;filesystem;thread` as a list with three entries.
[1] https://cmake.org/cmake/help/latest/command/find_package.html?highlight=components
[2] https://cmake.org/cmake/help/latest/command/list.html
=> CMake is not able to find boost components using wt-config.cmake

src/Wt/Dbo/Field.h, src/Wt/Dbo/Session.C, test/dbo/DboTest8.C
The RESTRICT foreign key constraint is supported by all the major databases.
It is a must have feature for quite a lot of database schemes.
It's implementation in the Wt::Dbo module is very straight forward process, so there is no apparent reason no  to do so.
Tested:
1. Wt compiles successfully 
2. SQLite3 - SQL generation for the tables works as expected
=> Implement "RESTRICT" foreign key constraint in Wt::Dbo module

src/Wt/Signals/signals.hpp, src/Wt/WSignal.h
This fix allows you to pass move-only objects as signal parameters. To do this, they are wrapped in std::forward(). In other words the parameters are perfectly forwarded.
An example use cases where this can be useful:
**Example emiting:**
`button->clicked().connect(
[this] { my_signal.emit(std::make_unique<Wt::WText>("Send this text widget by a signal")); });`
**Example Slot :**
`void contentLoad(std::unique_ptr<Wt::WWidget> widget)
{
root()->addWidget(std::move(widget));
}`
=> Perfect forwarding for Signal parameters

examples/mandelbrot/MandelbrotImage.C
call `done()` on `WRasterImage`
=> Fix examples/mandelbrot generation

src/Wt/Dbo/Impl.h, src/Wt/Dbo/Types.h
The Wt::Dbo::query_result_traits<> template was declared and defined as 'struct' in SqlTraits.h, but is declared as 'class' in the DBO_EXTERN_TEMPLATES and DBO_INSTANTIATE_TEMPLATES macros. This inconsistency causes multiple compiler warnings, such as [C4099](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-2-c4099?view=msvc-160) on Visual Studio 2017/2019., whenever the macros are used. Declaring as struct solves the issue.
=> Resolved an issue with DBO_EXTERN_TEMPLATES and DBO_INSTANTIATE_TEMPLATES 

src/Wt/Dbo/collection.h, src/Wt/Dbo/collection_impl.h, test/dbo/DboTest.C
This pull request covers/fixes several issues with Wt::Dbo::collection<>:
- The collection::iterator operator == may cause an access violation due to a missing null-check in the third case; this can occur if impl_ == nullptr && other.impl_ != nullptr && other.impl_.ended_ == false, which is not covered by the first 2 cases.
- collection::iterator and collection::const_iterator are derived from std::iterator, which is deprecated in C++17. Since deriving from std::iterator does nothing but adding some type definitions, adding those typedefs directly to iterator/const_iterator solves the deprecation issue while being fully compatible with C++14 and before.
- const_iterator declares the assignment operator operator = (iterator), but the definition is missing. I added one which mimics the …
=> Fixed several issues in Wt::Dbo::collection<>

src/web/WebSession.C
This pull request contains a fix for a segmentation fault during application creation, if the application create function used for an entry point returns a nullptr - as described in [Issue 10483](https://redmine.webtoolkit.eu/issues/10483).
=> Fixed a possible access violation in WebSession

src/Wt/WServer.h
WServer::waitForShutdown doesn't take a parameter.
=> Correct documented invocation

examples/blog/css/blog.css, examples/composer/composer.css, examples/feature/auth1/css/style.css, examples/feature/auth2/css/style.css, examples/feature/saml/css/style.css, examples/filetreetable/filetree.css, examples/qrlogin/css/style.css, examples/widgetgallery/docroot/style/everywidget.css, resources/form.css, resources/themes/default/wt.css, resources/themes/polished/wt.css, src/Wt/WApplication.C, src/web/DomElement.C
This pull requests contains some fixes for invalid HTML and CSS, which is automatically created by Wt - as described in [Issue 10482](https://redmine.webtoolkit.eu/issues/10482)
=> Fixed some invalid HTML/CSS

src/Wt/Dbo/FixedSqlConnectionPool.C
This pull request contains a fix for the missing timeout default initialization in `FixedSqlConnectionPool` - as described in [Issue 10543](https://redmine.webtoolkit.eu/issues/10543).
=> Added missing timeout default initialization in FixedSqlConnectionPool

src/Wt/WTable.C
I think the table should always be set here, right?
=> fix insertColumn

src/Wt/Json/Value.C, src/Wt/Json/Value.h
I don't see why JSON does not support long values.
I added a constructor that supports long values and the associated code.
=> Added support for long in json

src/Wt/WProgressBar.C, src/Wt/WProgressBar.h
This makes it possible to set "progress-bar-success" or "progress-bar-danger" on the inner bar div which is useful for some validation feedback.
=> Added support for updating the value style class of a WProgressBar

src/Wt/Dbo/backend/Postgres.C
I got a compiler error on my Debian 12 machine. Adding the missing #include fixes it:
```
[ 72%] Building CXX object src/Wt/Dbo/backend/CMakeFiles/wtdbopostgres.dir/Postgres.C.o
/home/deb/git/wt/src/Wt/Dbo/backend/Postgres.C: In function ‘std::string {anonymous}::double_to_s(double)’:
/home/deb/git/wt/src/Wt/Dbo/backend/Postgres.C:123:26: error: aggregate ‘std::array<char, 30> buf’ has incomplete type and cannot be defined
123 |     std::array<char, 30> buf;
|                          ^~~
/home/deb/git/wt/src/Wt/Dbo/backend/Postgres.C: In function ‘std::string {anonymous}::float_to_s(float)’:
/home/deb/git/wt/src/Wt/Dbo/backend/Postgres.C:148:26: error: aggregate ‘std::array<char, 30> buf’ has incomplete type and cannot be defined
148 |     std::array<char, 30> buf;
| …
```
=> add #include <array> to fix compiler error

fuzz/fuzz-eval.C
The fuzz-eval target contains an issue - missing return statement in a non-void function. According to the C++ standard, it's an undefined behavior:
> Flowing off the end of a function is equivalent to a return with no value; this results in undefined behavior in a value-returning function.
In practice, it leads to fuzzer crash:
```
==268678== ERROR: libFuzzer: deadly signal
#0 0x5589461e8ba1 in __sanitizer_print_stack_trace (fuzz-eval+0x763ba1)
#1 0x558946141558 in fuzzer::PrintStackTrace() (fuzz-eval+0x6bc558)
#2 0x558946127bf3 in fuzzer::Fuzzer::CrashCallback() (fuzz-eval+0x6a2bf3)
#3 0x7fdd3a1af51f  (/lib/x86_64-linux-gnu/libc.so.6+0x4251f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
#4 0x55894621dc78 in (anonymous namespace)::eval(std::__cxx11::basic_string<char, …
```
=> WT-13355: Fix fuzz-eval target: add missing return statement
